#ifndef UTILSCOMMONS_H_
#define UTILSCOMMONS_H_

#include<stdio.h>
#include<stdlib.h>
#include<signal.h>
#include<unistd.h>
#include<sys/socket.h>
#include<netdb.h>
#include<string.h>
#include<commons/log.h>
#include<commons/string.h>
#include<commons/config.h>


//Config
#define IP_APP "IP_APP"
#define IP_CLIENTE "IP_CLIENTE"
#define IP_COMANDA "IP_COMANDA"
#define IP_RESTAURANTE "IP_RESTAURANTE"
#define IP_SINDICATO "IP_SINDICATO"
#define PUERTO_APP "PUERTO_APP"
#define PUERTO_CLIENTE "PUERTO_CLIENTE"
#define PUERTO_COMANDA "PUERTO_COMANDA"
#define PUERTO_RESTAURANTE "PUERTO_RESTAURANTE"
#define PUERTO_SINDICATO "PUERTO_SINDICATO"


//Defino diferentes procesos
#define APP "APP"
#define CLIENTE "CLIENTE"
#define COMANDA "COMANDA"
#define RESTAURANTE "RESTAURANTE"
#define SINDICATO "SINDICATO"

//Mensajes
#define MENSAJE_CONSULTAR_RESTAURANTES "CONSULTAR_RESTAURANTES"
#define MENSAJE_SELECCIONAR_RESTAURANTE "SELECCIONAR_RESTAURANTE"
#define MENSAJE_OBTENER_RESTAURANTE "OBTENER_RESTAURANTE"
#define MENSAJE_CONSULTAR_PLATOS "CONSULTAR_PLATOS"
#define MENSAJE_CREAR_PEDIDO "CREAR_PEDIDO"
#define MENSAJE_GUARDAR_PEDIDO "GUARDAR_PEDIDO"
#define MENSAJE_AGREGAR_PLATO "AGREGAR_PLATO"
#define MENSAJE_CONFIRMAR_PEDIDO "CONFIRMAR_PEDIDO"
#define MENSAJE_PLATO_LISTO "PLATO_LISTO"
#define MENSAJE_CONSULTAR_PEDIDO "CONSULTAR_PEDIDO"
#define MENSAJE_OBTENER_PEDIDO "OBTENER_PEDIDO"
#define MENSAJE_FINALIZAR_PEDIDO "FINALIZAR_PEDIDO"
#define MENSAJE_TERMINAR_PEDIDO "TERMINAR_PEDIDO"
#define MENSAJE_GUARDAR_PLATO "GUARDAR_PLATO"

#define MENSAJE_RTA_CONSULTAR_RESTAURANTES "RTA_CONSULTAR_RESTAURANTES"
#define MENSAJE_RTA_SELECCIONAR_RESTAURANTE "RTA_SELECCIONAR_RESTAURANTE"
#define MENSAJE_RTA_OBTENER_RESTAURANTE "RTA_OBTENER_RESTAURANTE"
#define MENSAJE_RTA_CONSULTAR_PLATOS "RTA_CONSULTAR_PLATOS"
#define MENSAJE_RTA_CREAR_PEDIDO "RTA_CREAR_PEDIDO"
#define MENSAJE_RTA_GUARDAR_PEDIDO "RTA_GUARDAR_PEDIDO"
#define MENSAJE_RTA_AGREGAR_PLATO "RTA_AGREGAR_PLATO"
#define MENSAJE_RTA_CONFIRMAR_PEDIDO "RTA_CONFIRMAR_PEDIDO"
#define MENSAJE_RTA_PLATO_LISTO "RTA_PLATO_LISTO"
#define MENSAJE_RTA_CONSULTAR_PEDIDO "RTA_CONSULTAR_PEDIDO"
#define MENSAJE_RTA_OBTENER_PEDIDO "RTA_OBTENER_PEDIDO"
#define MENSAJE_RTA_FINALIZAR_PEDIDO "RTA_FINALIZAR_PEDIDO"
#define MENSAJE_RTA_TERMINAR_PEDIDO "RTA_TERMINAR_PEDIDO"
#define MENSAJE_RTA_GUARDAR_PLATO "RTA_GUARDAR_PLATO"

typedef enum{
	CONSULTAR_RESTAURANTES = 1, //no recibe nada
	RTA_CONSULTAR_RESTAURANTES = 2,
	SELECCIONAR_RESTAURANTE = 3,
	RTA_SELECCIONAR_RESTAURANTE = 4, //Confirmacion Ok/Fail
	OBTENER_RESTAURANTE= 5,//recibe solo restaurante
	RTA_OBTENER_RESTAURANTE= 6,
	CONSULTAR_PLATOS = 7, //recibe solo restaurante
	RTA_CONSULTAR_PLATOS = 8,
	CREAR_PEDIDO = 9, //no recibe nada
	RTA_CREAR_PEDIDO = 10, //retorna idPedido
	GUARDAR_PEDIDO = 11, //m_pedido
	RTA_GUARDAR_PEDIDO = 12, //retorna idPedido
	AGREGAR_PLATO = 13,
	RTA_AGREGAR_PLATO  = 14, //Confirmacion Ok/Fail
	GUARDAR_PLATO = 15,
	RTA_GUARDAR_PLATO = 16, //Confirmacion Ok/Fail
	CONFIRMAR_PEDIDO = 17, //recibe idPedido
	RTA_CONFIRMAR_PEDIDO = 18, //Confirmacion Ok/Fail
	PLATO_LISTO = 19,
	RTA_PLATO_LISTO = 20, //Confirmacion Ok/Fail
	CONSULTAR_PEDIDO = 21, //recibe idPedido
	RTA_CONSULTAR_PEDIDO = 22,
	OBTENER_PEDIDO = 23, //m_pedido
	RTA_OBTENER_PEDIDO = 24,
	FINALIZAR_PEDIDO = 25, //m_pedido,
	RTA_FINALIZAR_PEDIDO = 26, //Confirmacion Ok/Fail
	TERMINAR_PEDIDO = 27, //m_pedido,
	RTA_TERMINAR_PEDIDO = 28, //Confirmacion Ok/Fail
	POSICION_CLIENTE = 29,
}op_code;

typedef enum{ //son para saber el tipo de struct que usa cada mensaje
	STRC_MENSAJE_VACIO = 0,
	STRC_RESTAURANTE_Y_PLATO = 1,
	STRC_SELECCIONAR_RESTAURANTE = 2,
	STRC_ID_CONFIRMACION = 3,
	STRC_NOMBRE = 4,
	STRC_RTA_OBTENER_RESTAURANTE = 5,
	STRC_NOMBRE_ID = 6,
	STRC_PLATO_LISTO = 7,
	STRC_RTA_CONSULTAR_PEDIDO =8,
	STRC_RTA_OBTENER_PEDIDO =9,
	STRC_GUARDAR_PLATO = 10,
	STRC_POSICION = 11,
}struct_code;


t_log* iniciar_logger(t_config*);
t_config* leer_config(char* proceso);
void liberar_vector (char** vector);
char* op_code_to_string(op_code tipo_mensaje);
op_code string_to_op_code(char* tipo_mensaje);
struct_code op_code_to_struct_code(op_code tipo_mensaje);






#endif /* UTILS_H_ */

